### ISSUE TITLE
Memory Problem

### ISSUE THREAD

**Issue by Schucki** [spaniakos/ArduinoMD5#1]
This library allocates 35Bytes of Arduino SRAM every time you run the make_digest function. 
I ran Out of memory very quick.

**Comment by spaniakos** [comment]
what you mean you are out of ram very quick?
i have tried this library with intel galileo and arduinio leonardo with good results , can you show a sample sketch that you are using ?

**Comment by Schucki** [comment]
I was hashing a data every 15 seconds, and everytime the libray allocated another 35 bytes. So after half an hour my Arduino Mega2560 R3 freezed because there was no SRAM available.
This line in make_digest
char \* md5str = (char_) malloc(sizeof(char)_(len*2+1));
should be moved outside the function, so that it is only called once not every time a hash is calculated.

**Comment by spaniakos** [comment]
perhaps you are correct.
there is not a corresponding free function to the malloc.

perhaps i could try to allocate a specific string to use with this function and have a static char to manipulate.

i will try to code and the modificiations later this week , as i cannot do it today.
i will keep you updated in the next days for the result.

**Comment by Schucki** [comment]
i initialized the md5str outside the function, so it uses the same buffer every time it runs.
But, great library!

**Comment by spaniakos** [comment]
i forked it and enchanced it :D but thanks
and thanks for the comment on the memory ;)
